---
title: '클린업 3주차 패키지'
author: '조혜현'
date: '3/25/2021'
output: html_document
---

# Chapter1
# 문제0
```{r}
library(tidyverse)
library(data.table)
library(gridExtra)

setwd('C:/Users/iyuo1/OneDrive/Documents/P-SAT/클린업 패키지/3주차패키지')

data <- fread('data.csv')
test <- fread('test.csv') 
```

# 문제1
```{r}
head(data)

data %>% str()

data$bmi<-as.numeric(data$bmi)
colSums(is.na(data))

NAmean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
data <-replace(data, TRUE, lapply(data, NAmean))
colSums(is.na(data))
```

# 문제2
```{r}
data <- data %>% mutate_if(is.character,as.factor)
str(data)
```

# 문제3
```{r}
data <- data %>% select(-id)
str(data)
```

# 문제4
```{r}
df_fac<-data %>%
  gather(key='variable', value='value',
         c('gender', 'hypertension', 'heart_disease', 
           'ever_married','work_type', 'Residence_type', 'smoking_status'))


str1<-subset(df_fac, data$stroke==1)

stroke_plot_1 = ggplot(str1, aes(x=variable, fill=value))+
  geom_bar(position = 'fill', alpha=0.5)+
  coord_flip()+
  theme(panel.background = element_rect(fill = 'white', color = 'black', linetype = 'solid'),
        axis.title.x = element_text(face = 'bold', size = 8),
        axis.title.y = element_text(face = 'bold', size = 8),
        plot.title = element_text(face = 'bold', size = 10, hjust = 0.5),
        axis.text.x = element_text(face = 'bold', size = 8, colour = 'grey50'),
        axis.text.y = element_text(face = 'bold', size = 8, colour = 'grey50'),
        legend.position = 'bottom',
        legend.title = element_blank(),
        legend.key.size = unit(4,'mm'))+
  labs(x='variable', title = 'Stroke : 1')+
  guides(color=FALSE)


str2<-subset(df_fac, data$stroke==0)

stroke_plot_2 = ggplot(str2, aes(x=variable, fill=value))+
  geom_bar(position = 'fill', alpha=0.5)+
  coord_flip()+
  theme(panel.background = element_rect(fill = 'white', color = 'black', linetype = 'solid'),
        axis.title.x = element_text(face = 'bold', size = 8),
        axis.title.y = element_text(face = 'bold', size = 8),
        plot.title = element_text(face = 'bold', size = 10, hjust = 0.5),
        axis.text.x = element_text(face = 'bold', size = 8, colour = 'grey50'),
        axis.text.y = element_text(face = 'bold', size = 8, colour = 'grey50'),
        legend.position = 'bottom',
        legend.title = element_blank(),
        legend.key.size = unit(4,'mm'))+
  labs(x='variable', title = 'Stroke : 0')+
  guides(color=FALSE)

grid.arrange(stroke_plot_1, stroke_plot_2, ncol=2)
```

# 문제5
```{r}
stroke_plot_3 = data %>% select(where((is.numeric)),stroke) %>% gather(key='variable', value='value',-stroke) %>% filter(stroke==1) %>% ggplot(aes(x=value,color=variable)) + geom_density() + labs(title="stroke : 1",color='') + theme_bw() + theme(plot.title = element_text(hjust = 0.5)) 

stroke_plot_4 = data %>% select(where((is.numeric)),stroke) %>% gather(key='variable', value='value',-stroke) %>% filter(stroke==0) %>% ggplot(aes(x=value,color=variable)) + geom_density() + labs(title="stroke : 0",color='') + theme_bw() + theme(plot.title = element_text(hjust = 0.5)) 

grid.arrange(stroke_plot_3,stroke_plot_4,nrow=2)
```

# 문제7
```{r}
data <- data %>% select(-c(gender,Residence_type))
```

# 문제8
```{r}
mean_imputation = function(x){
    ifelse(is.na(x),mean(x,na.rm=T),x)}

test <- test %>% mutate(bmi=as.numeric(bmi)) %>% mutate(bmi=mean_imputation(bmi))
str(test)

test <- test %>% mutate_if(is.character,as.factor)
test <- test %>% mutate_if(is.integer,as.factor) 
str(test)

test <- test %>% select(-c(id,gender,Residence_type))
str(test)
```

# chapter2
# 문제0
```{r}
library(catboost)
library(caret)
library(MLmetrics)
```
### Catboost는 Ordered Boosting 방식을 따르고, Target Encoding, Mean Encoding, Response Encoding 이라고 불리우는 기법을 사용한다. Catboost는 범주형 변수를 처리하는데에 유용한 알고리즘이다. 파라미터에는 iterations, depth가 있다.

# 문제1
```{r}
logloss_cb <- expand.grid(depth = c(4, 6, 8), 
                          iterations=c(100,200), logloss = c(NA))
logloss_cb
```


# Chapter3

# 문제0
```{r}
library(factoextra)
library(cluster)
```

# 문제1
```{r}
new.data <- data %>% select(where(is.numeric)) %>% scale()
```

# 문제2
```{r}
fviz_nbclust(new.data, kmeans, method = "wss", k.max = 10)
fviz_nbclust(new.data, kmeans, method = "silhouette", k.max =10)
```

# 문제3
```{r}
set.seed(1234)
data.cluster<-kmeans(new.data, 3, nstart = 1, iter.max = 30)
fviz_cluster(data.cluster, data = new.data, stand=F)+theme(panel.background = element_rect(fill = "white",color = "black"))
```

# 문제4
```{r}
cluster.data = data %>% select(where(is.numeric)) %>% mutate(cluster= data.cluster$cluster) 

age.cluster = cluster.data %>% ggplot(aes(x=factor(cluster),y=age)) + geom_boxplot(outlier.shape = NA, alpha=0.5,fill=c("#ff5e78", "#ffc75f", "#845ec2"),color=c("#ff5e78", "#ffc75f", "#845ec2")) + stat_boxplot(geom='errorbar',color=c("#ff5e78", "#ffc75f", "#845ec2")) + labs(x='cluster') + theme(panel.background = element_rect(fill = "white",color = "black"))

glucose.cluster = cluster.data %>% ggplot(aes(x=factor(cluster),y=avg_glucose_level)) + geom_boxplot(outlier.shape = NA, alpha=0.5,fill=c("#ff5e78", "#ffc75f", "#845ec2"),color=c("#ff5e78", "#ffc75f", "#845ec2")) + stat_boxplot(geom='errorbar',color=c("#ff5e78", "#ffc75f", "#845ec2")) + labs(x='cluster') + theme(panel.background = element_rect(fill = "white",color = "black"))

bmi.cluster = cluster.data %>% ggplot(aes(x=factor(cluster),y=bmi)) + geom_boxplot(outlier.shape = NA, alpha=0.5,fill=c("#ff5e78", "#ffc75f", "#845ec2"),color=c("#ff5e78", "#ffc75f", "#845ec2")) + stat_boxplot(geom='errorbar',color=c("#ff5e78", "#ffc75f", "#845ec2")) + labs(x='cluster') + theme(panel.background = element_rect(fill = "white",color = "black"))

grid.arrange(age.cluster, glucose.cluster, bmi.cluster, ncol = 3)
```
